Add gke-windows-builder to build multi-arch Windows containers.
bendory/cloud-builders pull request #7
Opened 2021-10-29 06:52 UTC by YangLu1031

Make the gke-windows-builder official in Cloud Builders.

2021-11-04 23:17 UTC, YangLu1031 commented
[gke-windows-tools AR](https://console.cloud.google.com/artifacts?project=gke-windows-tools) is already public.

2021-11-04 23:18 UTC, YangLu1031 commented
/unhold

2021-11-04 23:41 UTC, pjh requested changes

2021-11-04 23:41 UTC, pjh commented on Preview/gke-windows-builder/README.md
> +# gke-windows-builder
Please run the mdformat tool on this file.

2021-11-04 23:41 UTC, pjh commented on Preview/gke-windows-builder/README.md
> +This `gke-windows-builder` build step is based on `us-docker.pkg.dev/gke-windows-tools/docker-repo/gke-windows-builder` image supplied by GKE Windows team at GoogleCloudPlatform/kubernetes-engine-win
Please link GoogleCloudPlatform/kubernetes-engine-windows-tools https://github.com/GoogleCloudPlatform/kubernetes-engine-windows-tools

2021-11-04 23:41 UTC, pjh commented on Preview/gke-windows-builder/README.md
> +    - 'us-docker.pkg.dev/$PROJECT_ID/docker-repo/windows-multiarch-container-demo:cloudbuild'
The Cloud Build service account is going to need an IAM role in order to push to `us-docker.pkg.dev/$PROJECT_ID/docker-repo`, right?

Please run through an example of using the builder to make sure these steps are complete. Consider removing all `@cloudbuild.gserviceaccount.com` IAM roles from your project before starting, to make sure you're simulating what a first-time user would have.

2021-11-04 23:41 UTC, pjh commented on Preview/gke-windows-builder/example/cloudbuild.yaml
> +  - name: 'us-docker.pkg.dev/gke-windows-tools/docker-repo/gke-windows-builder'
This should be `us-docker.pkg.dev/cloud-builders/preview/gke-windows-builder`, right?

2021-11-05 09:25 UTC, YangLu1031 commented on Preview/gke-windows-builder/README.md
> +This `gke-windows-builder` build step is based on `us-docker.pkg.dev/gke-windows-tools/docker-repo/gke-windows-builder` image supplied by GKE Windows team at GoogleCloudPlatform/kubernetes-engine-win
Done

2021-11-05 09:29 UTC, YangLu1031 commented on Preview/gke-windows-builder/README.md
> +    - 'us-docker.pkg.dev/$PROJECT_ID/docker-repo/windows-multiarch-container-demo:cloudbuild'
Reverted back and will do those steps later.

2021-11-09 06:47 UTC, YangLu1031 commented on Preview/gke-windows-builder/README.md
> +    - 'us-docker.pkg.dev/$PROJECT_ID/docker-repo/windows-multiarch-container-demo:cloudbuild'
Created https://github.com/GoogleCloudPlatform/kubernetes-engine-windows-tools/pull/6, so updated here.

2021-11-09 17:59 UTC, bendory commented on Preview/gke-windows-builder/example/Dockerfile
> +ARG WINDOWS_VERSION
Looks to me like there should be a default value for `WINDOWS_VERSION`?

I see no default value here and no value set in the `cloudbuild.yaml` -- does the `cloudbuild.yaml` work as written?

2021-11-09 18:06 UTC, pjh commented on Preview/gke-windows-builder/example/Dockerfile
> +ARG WINDOWS_VERSION
The gke-windows-builder adds this arg: https://github.com/GoogleCloudPlatform/kubernetes-engine-windows-tools/blob/6bb24f152dd7a238d62f0f86ac819f22229ff807/gke-windows-builder/builder/main.go#L312.

That said, @YangLu1031 could you add a comment here that explains this, to avoid confusion?

2021-11-10 08:32 UTC, YangLu1031 commented on Preview/gke-windows-builder/example/Dockerfile
> +ARG WINDOWS_VERSION
Ok, added

2021-11-11 21:53 UTC, merged